do Brokenline
rariblecom/protocol-contracts pull request #14
Opened 2021-04-16 16:56 UTC by SKonstantinS

Add cliff and tests, no optimization, but add it in future

2021-04-20 19:49 UTC, evgenynacu requested changes

2021-04-20 19:49 UTC, evgenynacu commented on broken-line/contracts/LibBrokenLine.sol
>      function add(BrokenLineDomain.BrokenLine storage brokenLine, BrokenLineDomain.Line memory line) internal {
а чем отличается эта функция от следующей add?
вроде, они должны одинаково работать, если cliff = 0. наверное, тогда одну оставить лучше

2021-04-20 19:49 UTC, evgenynacu commented on broken-line/contracts/LibBrokenLine.sol
> +            require (slope >= 0, "slope < 0, something wrong");
это бессмысленная проверка - slope unsigned

2021-04-20 19:49 UTC, evgenynacu commented on broken-line/contracts/LibBrokenLine.sol
> +            slope = uint(int(slope).add(brokenLine.slopeChanges[time]));
вот тут, наверное, стоит проверить, что slope будет >= 0 (перед cast)
вместо проверки на строке 72

2021-04-20 19:49 UTC, evgenynacu commented on broken-line/contracts/LibBrokenLine.sol
> +            brokenLine.slopeChanges[cliff] = brokenLine.slopeChanges[cliff].add(int(line.slope));
давай сверим, что правильно параметры используем
cliff - это delta (interval), когда разлочка не идет

тогда, наверное, в slopeChanges нужно писать значение в start + cliff?
а также, period - начинается после cliff (это тоже delta, за которое идет линейная разлочка)

2021-04-21 07:54 UTC, SKonstantinS commented on broken-line/contracts/LibBrokenLine.sol
> +            slope = uint(int(slope).add(brokenLine.slopeChanges[time]));
да согласен, вроде хотел как лучше, но получилось как всегда, правлю

2021-04-21 07:54 UTC, SKonstantinS commented on broken-line/contracts/LibBrokenLine.sol
> +            require (slope >= 0, "slope < 0, something wrong");
да согласен, правлю

2021-04-21 07:54 UTC, SKonstantinS commented on broken-line/contracts/LibBrokenLine.sol
> +            brokenLine.slopeChanges[cliff] = brokenLine.slopeChanges[cliff].add(int(line.slope));
я согласен полностью И насколько понимаю:
для cliff в slopeChanges[line.start + cliff] - вот "сюда" писать, это канеш "залет", ибо теста с start != 1 не было,  а должен был быть!!!
для period он разумеется сдвигается на cliff + line.start - это было сделано

2021-04-21 07:54 UTC, SKonstantinS commented on broken-line/contracts/LibBrokenLine.sol
>      function add(BrokenLineDomain.BrokenLine storage brokenLine, BrokenLineDomain.Line memory line) internal {
да, действительно согласен, оставляем одну

2021-04-22 06:56 UTC, evgenynacu requested changes

2021-04-22 06:56 UTC, evgenynacu commented on broken-line/contracts/LibBrokenLine.sol
> +        uint cliffIndex = line.start.add(cliff).sub(1);
это нужно перенести внутрь if и лучше назвать cliffEnd
+ есть вопрос: тут точно нужно отнимать 1? 
есть ли тест на то, что cliff = 1?
если нет, то его нужно добавить, проверить, что он работает так же, как и когда cliff = 0, но все сдвинуто на 1 шаг

2021-04-22 06:56 UTC, evgenynacu commented on broken-line/contracts/LibBrokenLine.sol
> +            int slopeChange = int(slope).add(brokenLine.slopeChanges[time]);
лучше назвать newSlope

2021-04-22 06:56 UTC, evgenynacu commented on broken-line/contracts/LibBrokenLine.sol
> +        brokenLine.slopeChanges[line.start.add(period).sub(1)] = brokenLine.slopeChanges[line.start.add(period).sub(1)].add(int(line.slope.sub(mod)).mul(-1));
тут и в следующей строке лучше не делать int(value).mul(-1)
лучше сделать функцию negate(uint value) returns (int) { return int(value) * -1 }
в mul еще проверки, они тут не нужны

2021-04-22 08:21 UTC, SKonstantinS commented on broken-line/contracts/LibBrokenLine.sol
> +        brokenLine.slopeChanges[line.start.add(period).sub(1)] = brokenLine.slopeChanges[line.start.add(period).sub(1)].add(int(line.slope.sub(mod)).mul(-1));
выполняю

2021-04-22 08:21 UTC, SKonstantinS commented on broken-line/contracts/LibBrokenLine.sol
> +            int slopeChange = int(slope).add(brokenLine.slopeChanges[time]);
выполняю

2021-04-22 09:49 UTC, SKonstantinS commented on broken-line/contracts/LibBrokenLine.sol
> +        uint cliffIndex = line.start.add(cliff).sub(1);
переношу в if

2021-04-22 10:19 UTC, merged