add Staking
rariblecom/protocol-contracts pull request #15
Opened 2021-04-20 16:02 UTC by SKonstantinS

First commit: add balanceOf, createLock methods.
LibBrokenLine.sol - its temporary in lib/

2021-04-20 19:54 UTC, evgenynacu requested changes

2021-04-20 19:54 UTC, evgenynacu commented on staking/contracts/Staking.sol
> +    mapping(uint => BrokenLineDomain.BrokenLine) public userBalances; //uint - idLock
тут, наверное, в mapping должно быть address => BrokenLine - это юзеры, то есть один BrokenLine на юзера
также totalBrokenLine должен быть, из которого легко считается totalSupply

при добавлении лока нужно добавлять Line в BrokenLine юзера + в total

2021-04-20 19:54 UTC, evgenynacu commented on staking/contracts/Staking.sol
> +        LibBrokenLine.add(userBalances[idLock], line);
если написать сверху using LibBrokenLine for LibBrokenLine.BrokenLine, то можно будет писать brokenLine.add(line)

2021-04-28 04:06 UTC, evgenynacu requested changes

2021-04-28 07:28 UTC, SKonstantinS commented on staking/contracts/Staking.sol
> +    using LibBrokenLine for BrokenLineDomain.BrokenLine;
ok

2021-04-28 10:29 UTC, SKonstantinS commented on staking/contracts/Staking.sol
> +    uint public idLock;
это id, вот щас он мне уже понадобился
позже сделю его вычисление более сложным чем ++

2021-04-28 10:30 UTC, SKonstantinS commented on staking/contracts/Staking.sol
> +    address[] usersAccounts;                                                //all user accounts
плохая идея - это очень мягко сказано, выпиливаю

2021-04-28 10:30 UTC, SKonstantinS commented on staking/contracts/Staking.sol
> +        require(slope != 0, "require slope deposit time not equal 0");
согласен, выпилил, обхожусь без нее

2021-04-28 10:35 UTC, SKonstantinS commented on staking/contracts/Staking.sol
> +        BrokenLineDomain.Line memory line = createLine(blockTime, amount, amount.div(period));
согласен НО мне нужен период для вычисления timestamp (в неделях) для фиксации в Lock et, для получения period=amount/slope,в общем без деления мне не обойтись пока (((

2021-04-28 15:07 UTC, SKonstantinS commented on staking/contracts/Staking.sol
> +    using LibBrokenLine for BrokenLineDomain.BrokenLine;
выполняю

2021-04-28 15:09 UTC, SKonstantinS commented on staking/contracts/Staking.sol
> +    mapping (address => Lock) usersLock;                                    //address - Lock
Да, делаю сколько угодно локов

2021-04-28 15:09 UTC, SKonstantinS commented on staking/contracts/Staking.sol
> +    constructor(IERC20Upgradeable _token, IERC20TransferProxy _proxy, address _deposite) public {
убираю IERC20TransferProxy

2021-04-28 15:10 UTC, SKonstantinS commented on staking/contracts/Staking.sol
> +        deposite = _deposite;
deposite убираю

2021-04-28 15:11 UTC, SKonstantinS commented on staking/contracts/Staking.sol
> +        BrokenLineDomain.Line memory line = createLine(blockTime, amount, amount.div(period));
либо предусмотреть, что в контракт будет приходить и slope и period

2021-05-12 19:12 UTC, merged